
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[415] =
    {   0,
        0,    0,    3,    3,    4,    4,    6,    6,   50,   48,
       45,   46,   48,   40,   33,   40,   48,   40,   28,   29,
       40,   40,   40,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   37,   38,    3,    3,    3,
        3,    3,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    4,    5,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    6,    6,    6,    6,    6,    6,    6,

        7,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,   47,   44,   39,   35,   34,    0,   29,   41,
       43,   42,   36,   36,   36,   36,   36,   36,   36,   36,
       17,   21,   36,   36,   36,   36,   36,   36,    3,    3,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    6,    6,    6,    8,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,   30,
       36,   36,   36,   36,   36,   19,   10,   22,   36,   36,
       36,   36,   36,   12,   11,   36,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,   25,   36,   18,

       36,   36,   36,   36,   15,   36,   36,   31,   36,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,   36,    9,   32,   24,   36,
       14,   36,   36,   20,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    6,    6,    6,    6,    6,    6,    6,    6,
        6,   36,   36,   36,   16,   27,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    6,    6,    6,    6,

        6,   26,   23,   13,    3,    3,    3,    4,    4,    4,
        6,    6,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    7,    1,    7,
        7,    8,    7,    7,    7,    9,   10,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    7,    1,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        7,    1,    7,    1,    1,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   16,   16,   26,   16,   27,
       28,   29,   16,   30,   31,   32,   33,   34,   35,   16,
       16,   16,   36,    7,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    4,    1,    1,
        5,    5,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[422] =
    {   0,
        0,    0,   37,    0,   74,    0,  111,    0,  776,  777,
      777,  777,  772,  760,  777,  777,  764,  141,  777,  141,
      758,  757,  756,    0,  741,  742,  741,  137,  133,  736,
      744,  732,  733,  745,  737,  777,  777,    0,    0,    0,
      757,  745,  752,    0,  748,  148,    0,  150,  742,  741,
      740,  170,  207,  138,  141,  164,  160,  161,  165,  166,
      171,  140,  172,    0,    0,    0,    0,  777,  750,  738,
        0,    0,  742,  194,    0,  214,  736,  735,  734,  244,
      281,  177,  201,  214,  191,  200,  211,  205,  206,  238,
      232,    0,    0,    0,    0,    0,  744,  732,    0,    0,

      735,  735,  253,    0,  253,  729,  728,  727,  318,  355,
      241,  242,  275,  249,  244,  272,  247,  269,  256,  274,
        0,    0,  777,  777,  777,  777,  777,  293,  301,  777,
      777,  777,    0,  712,  722,  707,  711,  708,  705,  707,
        0,  701,  707,  294,  701,  697,  304,  704,    0,    0,
        0,  777,    0,    0,    0,  295,  326,    0,    0,    0,
      700,  699,  312,  210,  288,  698,  311,  315,  697,  316,
      321,  319,  322,  338,  346,  350,    0,    0,    0,    0,
        0,  368,  373,    0,    0,    0,  696,  695,  360,  358,
      367,  694,  366,  370,  693,  335,  362,  382,  372,  373,

      377,  383,    0,    0,    0,  777,    0,    0,  401,  406,
        0,    0,    0,  692,  691,  392,  388,  395,  690,  394,
      398,  689,  399,  404,  411,  405,  408,  412,  409,  433,
      690,  684,  693,  682,  695,    0,    0,  690,  683,  689,
      675,  682,  685,    0,    0,  679,  435,  422,  421,  430,
      425,  437,  676,  675,  434,  432,  325,  433,  439,  442,
      674,  673,  443,  461,  448,  447,  456,  451,  440,  672,
      671,  459,  458,  353,  455,  464,  469,  670,  669,  465,
      483,  470,  471,  479,  473,  486,  668,  667,  484,  481,
      490,  478,  488,  494,  666,  665,  491,  671,  660,    0,

      669,  657,  665,  655,    0,  656,  658,    0,  663,  499,
      493,  655,  502,  497,  503,  500,  654,  505,  509,  653,
      513,  517,  511,  652,  519,  516,  523,  521,  651,  522,
      527,  650,  535,  536,  530,  649,  538,  537,  539,  540,
      648,  543,  547,  647,  549,  657,    0,    0,    0,  652,
      646,  644,  647,    0,  559,  641,  640,  639,  557,  553,
      555,  561,  638,  563,  637,  636,  635,  565,  562,  567,
      569,  634,  579,  633,  632,  631,  577,  573,  575,  581,
      630,  629,  621,  617,    0,    0,  583,  578,  585,  611,
      607,  587,  588,  592,  602,  596,  594,  595,  599,  589,

      572,    0,    0,    0,  532,  515,  453,  402,  376,  287,
      250,  196,  167,  777,  171,  627,  632,  637,  642,  647,
      652
    } ;

static const flex_int16_t yy_def[422] =
    {   0,
      414,    1,  414,    3,  414,    5,  414,    7,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  414,  414,  416,  416,  416,
      416,  416,  414,  416,  416,  416,  416,  416,  416,  416,
      416,  417,  417,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,  416,  416,  418,  418,  414,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  419,
      419,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,  418,  418,  420,  420,  420,  420,  420,  420,  420,

      414,  420,  420,  420,  420,  420,  420,  420,  421,  421,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      420,  420,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  416,  416,
      416,  414,  416,  416,  416,  416,  416,  416,  416,  416,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,

       81,   81,  420,  420,  420,  414,  420,  420,  420,  420,
      420,  420,  420,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  414,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  416,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,  418,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      420,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  415,  415,  415,  415,  415,
      415,  415,  415,  415,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   81,   81,   81,   81,   81,   81,   81,
       81,   81,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  415,  415,  415,  415,  415,   53,   53,   53,   53,
       53,   81,   81,   81,   81,   81,  110,  110,  110,  110,

      110,  415,  415,  415,   53,   53,   53,   81,   81,   81,
      110,  110,  110,    0,  414,  414,  414,  414,  414,  414,
      414
    } ;

static const flex_int16_t yy_nxt[815] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   24,   25,   26,   24,
       27,   28,   24,   24,   29,   24,   24,   24,   30,   31,
       32,   33,   24,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   52,   53,   54,   52,   55,   56,   52,
       52,   57,   52,   52,   52,   58,   59,   60,   61,   52,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       80,   81,   82,   80,   83,   84,   80,   80,   85,   80,

       80,   80,   86,   87,   88,   89,   80,   90,   91,   92,
       93,   94,   95,   96,   97,   98,   99,  100,  101,  102,
      103,  104,  105,  106,  107,  108,  109,  109,  110,  111,
      109,  112,  113,  109,  109,  114,  109,  109,  109,  115,
      116,  117,  118,  109,  119,  120,  121,  122,  126,  128,
      127,  129,  129,  137,  141,  154,  175,  155,  156,  142,
      157,  157,  138,  163,  139,  161,  164,  161,  161,  140,
      149,  149,  149,  149,  149,  133,  149,  149,  149,  149,
      165,  169,  149,  149,  149,  172,  170,  161,  161,  166,
      171,  167,  161,  161,  214,  176,  168,  173,  161,  161,

      174,  180,  189,  181,  187,  149,  149,  149,  149,  149,
      149,  149,  195,  149,  149,  149,  149,  196,  187,  149,
      149,  149,  182,  214,  183,  183,  190,  187,  187,  197,
      191,  198,  187,  187,  162,  200,  199,  161,  187,  192,
      250,  193,  149,  149,  177,  177,  194,  177,  177,  177,
      177,  177,  177,  177,  201,  202,  177,  177,  177,  187,
      126,  209,  208,  210,  210,  187,  216,  217,  214,  214,
      222,  214,  228,  224,  214,  223,  214,  214,  226,  177,
      177,  177,  177,  214,  177,  177,  177,  177,  177,  177,
      177,  218,  225,  177,  177,  177,  214,  229,  227,  214,

      219,  214,  220,  230,  230,  247,  247,  221,  188,  128,
      240,  129,  129,  251,  187,  161,  177,  177,  203,  203,
      203,  203,  203,  203,  203,  241,  203,  203,  249,  244,
      203,  203,  203,  245,  156,  257,  157,  157,  161,  161,
      253,  254,  161,  161,  317,  256,  161,  255,  161,  161,
      258,  259,  161,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  187,  203,  203,  161,  272,  203,  203,  203,
      260,  261,  329,  161,  263,  262,  266,  161,  264,  264,
      187,  182,  215,  183,  183,  187,  273,  187,  267,  187,
      203,  203,  268,  187,  187,  270,  271,  187,  274,  187,

      187,  276,  278,  187,  187,  277,  279,  280,  283,  187,
      187,  281,  281,  275,  209,  214,  210,  210,  284,  214,
      285,  214,  214,  287,  288,  214,  214,  291,  290,  187,
      289,  214,  214,  297,  293,  214,  214,  295,  214,  214,
      294,  296,  292,  230,  230,  247,  247,  310,  161,  161,
      312,  311,  161,  314,  315,  313,  326,  161,  316,  161,
      161,  161,  320,  319,  161,  318,  161,  187,  321,  161,
      161,  264,  264,  322,  187,  187,  324,  323,  187,  327,
      161,  325,  187,  187,  328,  187,  187,  330,  331,  332,
      333,  187,  187,  281,  281,  334,  187,  214,  214,  336,

      214,  335,  338,  337,  339,  214,  214,  340,  214,  341,
      342,  214,  343,  214,  344,  214,  345,  214,  214,  355,
      161,  214,  357,  356,  161,  359,  161,  161,  358,  161,
      161,  360,  161,  363,  361,  362,  161,  364,  187,  366,
      161,  365,  161,  187,  187,  368,  187,  367,  187,  187,
      187,  370,  369,  371,  187,  372,  373,  214,  375,  161,
      374,  377,  187,  214,  214,  214,  214,  214,  376,  381,
      214,  378,  379,  380,  214,  387,  214,  388,  389,  392,
      161,  390,  161,  391,  161,  393,  161,  394,  161,  187,
      187,  396,  187,  395,  187,  397,  187,  398,  399,  214,

      214,  400,  214,  401,  214,  161,  214,  406,  214,  405,
      161,  407,  161,  408,  187,  187,  214,  409,  410,  187,
      411,  214,  214,  187,  412,  413,  214,  149,  149,  187,
      149,  149,  161,  161,  161,  161,  161,  177,  161,  177,
      177,  177,  187,  404,  187,  187,  187,  203,  203,  203,
      403,  203,  214,  214,  214,  402,  214,  214,  214,  214,
      214,  187,  187,  187,  187,  161,  161,  161,  161,  386,
      385,  384,  383,  382,  214,  214,  214,  187,  187,  187,
      161,  161,  161,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  214,  214,  214,  214,  187,  187,  187,  187,

      161,  161,  161,  161,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  214,  286,  282,  214,
      187,  269,  265,  187,  161,  252,  248,  161,  246,  243,
      242,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      213,  212,  211,  207,  206,  205,  204,  186,  185,  184,
      179,  178,  123,  160,  159,  158,  153,  152,  151,  150,
      148,  147,  146,  145,  144,  143,  136,  135,  134,  132,
      131,  130,  125,  124,  123,  414,    9,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414
    } ;

static const flex_int16_t yy_chk[815] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,   18,   20,
       18,   20,   20,   28,   29,   46,   62,   46,   48,   29,
       48,   48,   28,   54,   28,   54,   55,   62,   55,   28,
       52,   52,   52,   52,   52,  415,   52,   52,   52,   52,
       56,   57,   52,   52,   52,   59,   57,   57,   58,   56,
       58,   56,   59,   60,  413,   63,   56,   60,   61,   63,

       61,   74,   82,   74,   82,   52,   52,   53,   53,   53,
       53,   53,   85,   53,   53,   53,   53,   85,   85,   53,
       53,   53,   76,  412,   76,   76,   83,   86,   83,   86,
       84,   87,   88,   89,   53,   89,   88,  164,   87,   84,
      164,   84,   53,   53,   80,   80,   84,   80,   80,   80,
       80,   80,   80,   80,   90,   91,   80,   80,   80,   91,
      103,  105,  103,  105,  105,   90,  111,  112,  111,  112,
      114,  115,  119,  115,  117,  114,  114,  411,  117,   80,
       80,   81,   81,  119,   81,   81,   81,   81,   81,   81,
       81,  113,  116,   81,   81,   81,  118,  120,  118,  116,

      113,  120,  113,  128,  128,  156,  156,  113,   81,  129,
      144,  129,  129,  165,  410,  165,   81,   81,  109,  109,
      109,  109,  109,  109,  109,  144,  109,  109,  163,  147,
      109,  109,  109,  147,  157,  172,  157,  157,  167,  163,
      167,  168,  168,  170,  257,  171,  172,  170,  171,  173,
      172,  173,  257,  109,  109,  110,  110,  110,  110,  110,
      110,  110,  196,  110,  110,  174,  196,  110,  110,  110,
      174,  175,  274,  175,  176,  175,  189,  176,  182,  182,
      274,  183,  110,  183,  183,  190,  197,  189,  190,  197,
      110,  110,  191,  193,  191,  193,  194,  194,  198,  199,

      200,  199,  201,  409,  201,  200,  201,  202,  216,  198,
      202,  209,  209,  198,  210,  217,  210,  210,  217,  216,
      218,  220,  218,  220,  221,  221,  223,  225,  224,  408,
      223,  224,  226,  229,  226,  227,  229,  228,  225,  228,
      227,  228,  225,  230,  230,  247,  247,  248,  249,  248,
      250,  249,  251,  252,  255,  251,  269,  250,  256,  256,
      258,  255,  260,  259,  252,  258,  259,  269,  263,  260,
      263,  264,  264,  265,  266,  265,  267,  266,  268,  272,
      407,  268,  275,  267,  273,  273,  272,  275,  276,  277,
      280,  276,  280,  281,  281,  282,  277,  282,  283,  284,

      285,  283,  286,  285,  289,  292,  284,  290,  290,  291,
      292,  289,  293,  286,  294,  293,  297,  291,  297,  310,
      311,  294,  313,  311,  314,  315,  310,  316,  314,  313,
      315,  316,  318,  321,  318,  319,  319,  322,  323,  325,
      321,  323,  406,  326,  322,  327,  325,  326,  328,  330,
      327,  330,  328,  331,  331,  333,  334,  335,  337,  405,
      335,  339,  333,  334,  338,  337,  339,  340,  338,  345,
      342,  340,  342,  343,  343,  355,  345,  359,  360,  364,
      360,  361,  361,  362,  359,  368,  355,  369,  362,  369,
      364,  371,  368,  370,  370,  373,  371,  377,  378,  401,

      378,  379,  379,  380,  377,  388,  373,  388,  380,  387,
      387,  389,  389,  392,  392,  393,  400,  393,  394,  394,
      397,  397,  398,  396,  398,  399,  399,  416,  416,  395,
      416,  416,  417,  417,  391,  417,  417,  418,  390,  418,
      418,  418,  419,  384,  419,  419,  419,  420,  420,  420,
      383,  420,  421,  421,  421,  382,  421,  381,  376,  375,
      374,  372,  367,  366,  365,  363,  358,  357,  356,  353,
      352,  351,  350,  346,  344,  341,  336,  332,  329,  324,
      320,  317,  312,  309,  307,  306,  304,  303,  302,  301,
      299,  298,  296,  295,  288,  287,  279,  278,  271,  270,

      262,  261,  254,  253,  246,  243,  242,  241,  240,  239,
      238,  235,  234,  233,  232,  231,  222,  219,  215,  214,
      195,  192,  188,  187,  169,  166,  162,  161,  148,  146,
      145,  143,  142,  140,  139,  138,  137,  136,  135,  134,
      108,  107,  106,  102,  101,   98,   97,   79,   78,   77,
       73,   70,   69,   51,   50,   49,   45,   43,   42,   41,
       35,   34,   33,   32,   31,   30,   27,   26,   25,   23,
       22,   21,   17,   14,   13,    9,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "d.l"
#line 2 "d.l"
#include <stdlib.h>
#include "y.tab.h"
//#define DEBUG
void yyerror(char *);
int maxTempStringLength = 10;
int currentTempStringLength = 0;
char* tempString;
void initScanner(void);
void initTempString(void);
void extendTempString(void);

#define TABLE_SIZE 256
#define FNV_OFFSET 14695981039346656037UL
#define FNV_PRIME 1099511628211UL
#define NODE_INT 0
#define NODE_FLOAT 1
#define NODE_BOOL 2
#define NODE_STRING 3
#define NODE_ARRAY 4
#define NODE_FUNCTION_WITH_NO_RETURN_VALUE 5
#define NODE_FUNCTION_WITH_RETURN_VALUE 6
#define NODE_CLASS 7

typedef struct TN {
	char* string;
	int type;
	int subType;
	int* argumentTypes;
	int argumentNum;
	int constant;
	int constantValue;
	int global;
	int index;
	struct TN* next;
} TableNode;

typedef struct ST {
	TableNode** table;
	struct ST* next;
	struct ST* previous;
	int globalTable;
	int startingVariableIndex;
} SymbolTable;

SymbolTable* symbolTable;

long long int hash(const char* key);
TableNode* lookUpInThisScope(const char* key);
TableNode* lookUpInEveryScope(const char* key);
TableNode* insert(const char* key, int type, int subType, int* argumentTypes, int argumentNum, int constant, int constantValue);
void createNewTable(int globalTable);
void popTable();
void printOneTable();
void printAllTables();

int lineCount;
int nextVariableIndex;
#line 817 "lex.yy.c"

#line 819 "lex.yy.c"

#define INITIAL 0
#define STRING_MODE 1
#define COMMAND_MODE_1 2
#define COMMAND_MODE_2 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 61 "d.l"

#line 1041 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 415 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 777 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "d.l"
{
														if (currentTempStringLength + 1 >= maxTempStringLength) {
															extendTempString();
														}
														tempString[currentTempStringLength] = '\"';
														currentTempStringLength++;
													}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "d.l"
{
														BEGIN 0;
														tempString[currentTempStringLength] = '\0';
														yylval.stringValue = tempString;
														return STRING; 
													}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 75 "d.l"
{
														int yytextLength = strlen(yytext);
														while (currentTempStringLength + yytextLength >= maxTempStringLength) {
															extendTempString();
														}
														if (tempString[0] == '\0') {
															for (int i = 0; i < yytextLength; i++) {
																tempString[i] = yytext[i];
															}
														}
														else {
															for (int i = 0; i < yytextLength; i++) {
																tempString[currentTempStringLength + i + 1] = yytext[i];
															}
														}
														currentTempStringLength += yytextLength;

														// Check how many lines does it have
														for (int i = 0; i < strlen(yytext); i++) {
															if (yytext[i] == '\n') {
																lineCount++;
															}
														}
													}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "d.l"
;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 100 "d.l"
{ BEGIN 0; lineCount++; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 101 "d.l"
{
														// Check how many lines does it have
														for (int i = 0; i < strlen(yytext); i++) {
															if (yytext[i] == '\n') {
																lineCount++;
															}
														}
													}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "d.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "d.l"
{ BEGIN 0; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "d.l"
{ return CLASS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "d.l"
{ return FUN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "d.l"
{ return VAR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "d.l"
{ return VAL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "d.l"
{ return PRINTLN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "d.l"
{ return PRINT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "d.l"
{ return READ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "d.l"
{ return RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "d.l"
{ return IF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "d.l"
{ return ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "d.l"
{ return FOR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "d.l"
{ return WHILE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "d.l"
{ return IN; }
	YY_BREAK
case 22:
#line 125 "d.l"
case 23:
YY_RULE_SETUP
#line 125 "d.l"
{ yylval.type = NODE_INT; return TYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "d.l"
{ yylval.type = NODE_FLOAT; return TYPE; }
	YY_BREAK
case 25:
#line 128 "d.l"
case 26:
YY_RULE_SETUP
#line 128 "d.l"
{ yylval.type = NODE_BOOL; return TYPE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "d.l"
{ yylval.type = NODE_STRING; return TYPE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "d.l"
{ yylval.intValue = atoi(yytext); return INTEGER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "d.l"
{ yylval.intValue = atoi(yytext); return INTEGER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "d.l"
{ yylval.floatValue = atof(yytext); return FLOAT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "d.l"
{ yylval.boolValue = 1; return BOOLEAN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "d.l"
{ yylval.boolValue = 0; return BOOLEAN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "d.l"
{ BEGIN STRING_MODE; initTempString(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "d.l"
{ BEGIN COMMAND_MODE_1; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "d.l"
{ BEGIN COMMAND_MODE_2; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "d.l"
{ 
														yylval.identifierName = (char*)malloc(sizeof(char) * (strlen(yytext) + 1)); 
														for (int i = 0; i < strlen(yytext); i++) {
															yylval.identifierName[i] = yytext[i];
														}
														yylval.identifierName[strlen(yytext)] = '\0';
														return IDENTIFIER; 
													}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 146 "d.l"
{ return *yytext; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 147 "d.l"
{ return *yytext; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 148 "d.l"
{ return DD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "d.l"
{ return *yytext; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 150 "d.l"
{ return LE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 151 "d.l"
{ return GE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "d.l"
{ return EQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 153 "d.l"
{ return NE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 154 "d.l"
;
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 155 "d.l"
{ lineCount++; }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 156 "d.l"
{ lineCount++; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 157 "d.l"
{
														yyerror("invalid character");
													}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 160 "d.l"
ECHO;
	YY_BREAK
#line 1392 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING_MODE):
case YY_STATE_EOF(COMMAND_MODE_1):
case YY_STATE_EOF(COMMAND_MODE_2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 415 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 415 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 414);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 160 "d.l"

void initTempString(void) {
	currentTempStringLength = 0;
	tempString[0] = '\0';
}
void extendTempString(void) {
	char* newString = (char*)malloc(sizeof(char) * maxTempStringLength * 2);
	for (int i = 0; i < maxTempStringLength; i++) {
		newString[i] = tempString[i];
	}
	free(tempString);
	tempString = newString;
	maxTempStringLength *= 2;
}
int yywrap(void) {
	return 1;
}
void initScanner(void) {
	tempString = (char*)malloc(sizeof(char) * maxTempStringLength);
	tempString[0] = '\0';
	symbolTable = (SymbolTable*)malloc(sizeof(SymbolTable));
	symbolTable -> table = (TableNode**)malloc(sizeof(TableNode*) * TABLE_SIZE);
	for (int i = 0; i < TABLE_SIZE; i++) {
		symbolTable -> table[i] = NULL;
	}
	symbolTable -> globalTable = 1;
	symbolTable -> next = NULL;
	symbolTable -> previous = NULL;
	lineCount = 1;
	nextVariableIndex = 0;
}

// Return 64-bit FNV-1a hash for key (NUL-terminated). See description:
// https://en.wikipedia.org/wiki/Fowler–Noll–Vo_hash_function
long long int hash(const char* key)
{
	long long int hashValue = FNV_OFFSET;
	for (const char* p = key; *p; p++) {
		hashValue ^= (long long int)(unsigned char)(*p);
		hashValue *= FNV_PRIME;
	}
	return hashValue;
}

TableNode* lookUpInThisScope(const char* key) {
#ifdef DEBUG
	printf("Look Up this Scope for %s\n", key);
	printAllTables();
#endif
	long long int index = hash(key) % TABLE_SIZE;
	TableNode** table = symbolTable -> table;
	while(index < 0)
	{
		index += TABLE_SIZE;
	}
	if (table[index] != NULL)
	{
		TableNode* currentNode = table[index];
		if (strcmp(currentNode -> string, key) == 0)
		{
			return currentNode;
		}
		while(currentNode -> next != NULL)
		{
			currentNode = currentNode -> next;
			if (strcmp(currentNode -> string, key) == 0)
			{
				return currentNode;
			}
		}
	}
	return NULL;
}

TableNode* lookUpInEveryScope(const char* key) {
#ifdef DEBUG
	printf("Look Up Every Scope for %s\n", key);
	printAllTables();
	//printf("Start %s: \n", key);
#endif
	SymbolTable* currentSymbolTable = symbolTable;
	while (currentSymbolTable != NULL) {
		long long int index = hash(key) % TABLE_SIZE;
		TableNode** table = currentSymbolTable -> table;
		while(index < 0)
		{
			index += TABLE_SIZE;
		}
		if (table[index] != NULL)
		{
			TableNode* currentNode = table[index];
#ifdef DEBUG
			//printf("(%s, %s)\n", currentNode -> string, key);
#endif
			if (strcmp(currentNode -> string, key) == 0)
			{
				return currentNode;
			}
			while(currentNode -> next != NULL)
			{
				currentNode = currentNode -> next;
				if (strcmp(currentNode -> string, key) == 0)
				{
					return currentNode;
				}
			}
		}
		currentSymbolTable = currentSymbolTable -> previous;
	}
	return NULL;
}

TableNode* insert(const char* key, int type, int subType, int* argumentTypes, int argumentNum, int constant, int constantValue) {
#ifdef DEBUG
	printf("INSERT %s\n", key);
#endif
	long long int foundIndex = hash(key) % TABLE_SIZE;
	while(foundIndex < 0)
	{
		foundIndex += TABLE_SIZE;
	}
	TableNode* newNode = (TableNode*)malloc(sizeof(TableNode));
	newNode -> string = (char*)malloc(sizeof(char) * (strlen(key) + 1));
	newNode -> string[0] = '\0';
	newNode -> argumentTypes = argumentTypes;
	newNode -> argumentNum = argumentNum;
	newNode -> type = type;
	newNode -> subType = subType;
	newNode -> constant = constant;
	newNode -> constantValue = constantValue;
	if (symbolTable -> globalTable) {
		newNode -> global = 1;
		newNode -> index = -1;
	} else {
		newNode -> global = 0;
		if ((type == NODE_INT || type == NODE_BOOL) && constant == 0) {
			newNode -> index = nextVariableIndex;
			nextVariableIndex ++;
		} else {
			newNode -> index = -1;
		}
	}
	strcat(newNode -> string, key);
	newNode -> next = NULL;

	TableNode* currentNode = symbolTable -> table[foundIndex];
	if (currentNode != NULL)
	{
		while(currentNode -> next != NULL)
		{
			currentNode = currentNode -> next;
		}
		currentNode -> next = newNode;
	}
	else
	{
		symbolTable -> table[foundIndex] = newNode;
	}
	return newNode;
}

void createNewTable(int globalTable) {
	SymbolTable* newTable = (SymbolTable*)malloc(sizeof(SymbolTable));
	newTable -> table = (TableNode**)malloc(sizeof(TableNode*) * TABLE_SIZE);
	for (int i = 0; i < TABLE_SIZE; i++)
	{
		newTable -> table[i] = NULL;
	}
	newTable -> globalTable = globalTable;
	newTable -> startingVariableIndex = nextVariableIndex;
	newTable -> next = NULL;
	symbolTable -> next = newTable;
	newTable -> previous = symbolTable;
	symbolTable = symbolTable -> next;
}

void popTable() {
	nextVariableIndex = symbolTable -> startingVariableIndex;
	SymbolTable* poppedTable = symbolTable;
	symbolTable = symbolTable -> previous;
	for (int i = 0; i < TABLE_SIZE; i++) {
		while (poppedTable -> table[i] != NULL) {
			free(poppedTable -> table[i] -> string);
			free(poppedTable -> table[i] -> argumentTypes);
			TableNode* nextTable = poppedTable -> table[i] -> next;
			free(poppedTable -> table[i]);
			poppedTable -> table[i] = nextTable;
		}
	}
	free(poppedTable -> table);
	free(poppedTable);
}

void printOneTable(SymbolTable* symbolTable) {
	TableNode** table = symbolTable -> table;
	for (int i = 0; i < TABLE_SIZE; i++) {
		if (table[i] != NULL) {
			TableNode* currentNode = table[i];
			while(currentNode != NULL) {
				printf("%s\t\t\t%d\n", currentNode -> string, currentNode -> index);
				currentNode = currentNode -> next;
			}
		}
	}
}

void printAllTables() {
	SymbolTable* currentSymbolTable = symbolTable;
	printf("\nTABLES: \n");
	printf("------------------------------\n");
	while(currentSymbolTable != NULL) {
		printOneTable(currentSymbolTable);
		currentSymbolTable = currentSymbolTable -> previous;
		printf("------------------------------\n");
	}
}

